"""add index on owner_id and start_time

Revision ID: b4144c4eb4f3
Revises: 7a5c1f546c96
Create Date: 2026-07-22 21:52:42.019967

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b4144c4eb4f3'
down_revision = '7a5c1f546c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_meetings_owner_id'),
            ['owner_id'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_meetings_start_time'),
            ['start_time'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_start_time'))
        batch_op.drop_index(batch_op.f('ix_meetings_owner_id'))

    # ### end Alembic commands ###
